const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="viscountkimutai@gmail.com"
global.location="nairobi,Kenya."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Africa/Nairobi";
global.github=process.env.GITHUB|| "https://github.com/king-ibrahim-md/KING-IBRAHIM-GPT";
global.gurl  =process.env.GURL  || "https://chat.whatsapp.com/L7T4iMvnfwCA8oLkUIRCFj";
global.website=process.env.GURL || "https://chat.whatsapp.com/L7T4iMvnfwCA8oLkUIRCFj" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/schizard00-bot-01-15" ; // SET LOGO FOR IMAGE 



global.devs = "254728782591" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "admin";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "254710772666";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '1',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "true"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 5,
global.disablepm = process.env.DISABLE_PM || "true",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "https://telegra.ph/schizard00-bot-01-15",
global.waPresence= process.env.WAPRESENCE ||  "available" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "true"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "25410772666,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://qr-scan.giftedtechnexus.co.ke/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Gifted Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "schizard MD 2024" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ ɢɪғᴛᴇᴅ ᴛᴇᴄʜ 』```", //*『sᴜʙsᴄʀɪʙᴇ • ɢɪғᴛᴇᴅ ᴛᴇᴄʜ』*\n https://whatsapp.com/channel/0029VaJmfmTDJ6H7CmuBss0o"),
 
  author : process.env.PACK_AUTHER|| "schizard00",
  packname: process.env.PACK_NAME || "👑",
  botname : process.env.BOT_NAME  || "schizard md",
  ownername:process.env.OWNER_NAME|| "It's schizard",

  sessionName:process.env.SESSION_ID || "SUHAIL_12_51_01_15_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOCxcbiAgICAgICAgODMsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTE5LFxuICAgICAgICA3NCxcbiAgICAgICAgMTI3LFxuICAgICAgICA3MixcbiAgICAgICAgMTY1LFxuICAgICAgICAxMCxcbiAgICAgICAgNzMsXG4gICAgICAgIDkwLFxuICAgICAgICAyNDIsXG4gICAgICAgIDIyLFxuICAgICAgICAxODksXG4gICAgICAgIDc1LFxuICAgICAgICA2MixcbiAgICAgICAgMjQsXG4gICAgICAgIDY5LFxuICAgICAgICA0NixcbiAgICAgICAgMTkzLFxuICAgICAgICAxNjAsXG4gICAgICAgIDI1NCxcbiAgICAgICAgNTUsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjUsXG4gICAgICAgIDQ0LFxuICAgICAgICAyMSxcbiAgICAgICAgMjExLFxuICAgICAgICAyMDgsXG4gICAgICAgIDg2LFxuICAgICAgICAyMzcsXG4gICAgICAgIDEwN1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMzEsXG4gICAgICAgIDQsXG4gICAgICAgIDk5LFxuICAgICAgICA4NCxcbiAgICAgICAgMTcwLFxuICAgICAgICA5NSxcbiAgICAgICAgMTA3LFxuICAgICAgICAzMSxcbiAgICAgICAgMjE4LFxuICAgICAgICAyMzUsXG4gICAgICAgIDM0LFxuICAgICAgICAyMTcsXG4gICAgICAgIDY4LFxuICAgICAgICAxNzEsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMTA5LFxuICAgICAgICAyMixcbiAgICAgICAgMjMyLFxuICAgICAgICAzLFxuICAgICAgICAzMyxcbiAgICAgICAgODksXG4gICAgICAgIDI1NCxcbiAgICAgICAgNjIsXG4gICAgICAgIDE4MCxcbiAgICAgICAgNTEsXG4gICAgICAgIDExNSxcbiAgICAgICAgMTMzLFxuICAgICAgICAxNTMsXG4gICAgICAgIDE1NixcbiAgICAgICAgMjI3LFxuICAgICAgICAxLFxuICAgICAgICAyNlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYsXG4gICAgICAgIDE5MCxcbiAgICAgICAgNzQsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTQwLFxuICAgICAgICAyMTIsXG4gICAgICAgIDcyLFxuICAgICAgICAxMzksXG4gICAgICAgIDgzLFxuICAgICAgICAxMDksXG4gICAgICAgIDUwLFxuICAgICAgICAyMTgsXG4gICAgICAgIDE0NixcbiAgICAgICAgMzcsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTM0LFxuICAgICAgICA2MixcbiAgICAgICAgMjA1LFxuICAgICAgICAzOCxcbiAgICAgICAgMzMsXG4gICAgICAgIDE0NixcbiAgICAgICAgOTIsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjA3LFxuICAgICAgICAxMyxcbiAgICAgICAgMTI0LFxuICAgICAgICAzOSxcbiAgICAgICAgOTIsXG4gICAgICAgIDExLFxuICAgICAgICAzMixcbiAgICAgICAgMTUyLFxuICAgICAgICAxMDNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzIsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMTgyLFxuICAgICAgICAxNTQsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTE0LFxuICAgICAgICAxMzQsXG4gICAgICAgIDU5LFxuICAgICAgICA2OSxcbiAgICAgICAgMTY3LFxuICAgICAgICAxOTQsXG4gICAgICAgIDEwLFxuICAgICAgICAxNTcsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTM1LFxuICAgICAgICAxMDcsXG4gICAgICAgIDczLFxuICAgICAgICAxMCxcbiAgICAgICAgNTEsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxNDAsXG4gICAgICAgIDE4LFxuICAgICAgICAxNixcbiAgICAgICAgODQsXG4gICAgICAgIDY3LFxuICAgICAgICA0OCxcbiAgICAgICAgMTUsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTQzLFxuICAgICAgICA0NCxcbiAgICAgICAgNjhcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTc1LFxuICAgICAgICAxMDQsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjA1LFxuICAgICAgICAyMTUsXG4gICAgICAgIDI3LFxuICAgICAgICAyMDUsXG4gICAgICAgIDExOSxcbiAgICAgICAgMTgsXG4gICAgICAgIDM3LFxuICAgICAgICAxNDksXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTc4LFxuICAgICAgICA3NyxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxOTYsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTc5LFxuICAgICAgICAxNTMsXG4gICAgICAgIDgwLFxuICAgICAgICAxODEsXG4gICAgICAgIDI4LFxuICAgICAgICA5NSxcbiAgICAgICAgMTI3LFxuICAgICAgICA0MixcbiAgICAgICAgNzgsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTA3LFxuICAgICAgICAyMDIsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTE1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzLFxuICAgICAgICAyMDYsXG4gICAgICAgIDYwLFxuICAgICAgICAyMzksXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTE2LFxuICAgICAgICA3MSxcbiAgICAgICAgNjAsXG4gICAgICAgIDE4NixcbiAgICAgICAgODEsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMzAsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTk3LFxuICAgICAgICA5OCxcbiAgICAgICAgMTUzLFxuICAgICAgICAxNTAsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTAsXG4gICAgICAgIDQ5LFxuICAgICAgICAxMSxcbiAgICAgICAgMTI5LFxuICAgICAgICAxODUsXG4gICAgICAgIDIsXG4gICAgICAgIDcwLFxuICAgICAgICA4LFxuICAgICAgICA5NSxcbiAgICAgICAgNjMsXG4gICAgICAgIDM0LFxuICAgICAgICA1OSxcbiAgICAgICAgMTE2LFxuICAgICAgICA0NVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAzMixcbiAgICAgICAgICAxNjksXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgMTAxLFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDgyLFxuICAgICAgICAgIDE1MCxcbiAgICAgICAgICAyMjcsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDk2XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDI0MyxcbiAgICAgICAgICA5NixcbiAgICAgICAgICAxOTcsXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICA3LFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICA3OSxcbiAgICAgICAgICA1MyxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgMjksXG4gICAgICAgICAgMTgwLFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgMjA3LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDE4OSxcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAyNTUsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDI0MyxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgNzRcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNjAsXG4gICAgICAgIDExMCxcbiAgICAgICAgNzgsXG4gICAgICAgIDYxLFxuICAgICAgICA1OCxcbiAgICAgICAgNDgsXG4gICAgICAgIDU4LFxuICAgICAgICAyMTMsXG4gICAgICAgIDEyOCxcbiAgICAgICAgODAsXG4gICAgICAgIDY1LFxuICAgICAgICAxOTUsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTk4LFxuICAgICAgICAxMjEsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTAzLFxuICAgICAgICA0OSxcbiAgICAgICAgNTYsXG4gICAgICAgIDE1OSxcbiAgICAgICAgNzksXG4gICAgICAgIDE4MixcbiAgICAgICAgMTg2LFxuICAgICAgICAxMjgsXG4gICAgICAgIDk5LFxuICAgICAgICAxNDUsXG4gICAgICAgIDEwMixcbiAgICAgICAgMjU0LFxuICAgICAgICA3NyxcbiAgICAgICAgMTg0LFxuICAgICAgICAyNDEsXG4gICAgICAgIDYzLFxuICAgICAgICAxMDMsXG4gICAgICAgIDE0OSxcbiAgICAgICAgOTcsXG4gICAgICAgIDMsXG4gICAgICAgIDc0LFxuICAgICAgICAxNDEsXG4gICAgICAgIDE1NixcbiAgICAgICAgMjMxLFxuICAgICAgICAzMSxcbiAgICAgICAgMTQsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTY2LFxuICAgICAgICA3MSxcbiAgICAgICAgMTAyLFxuICAgICAgICAyMzIsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTk0LFxuICAgICAgICAxMjIsXG4gICAgICAgIDE5MyxcbiAgICAgICAgNDYsXG4gICAgICAgIDQxLFxuICAgICAgICAxMzAsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTk2LFxuICAgICAgICAxNjQsXG4gICAgICAgIDE0NixcbiAgICAgICAgMjYsXG4gICAgICAgIDg0LFxuICAgICAgICAxOTIsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMzcsXG4gICAgICAgIDVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDY3LFxuICBcImFkdlNlY3JldEtleVwiOiBcIi9ZbmtBMDZwaGhSZWswdkJ2c2pBNVZrVlloWEpDZjR1b1lUL3o2NWZId1U9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjU0Nzg0MzU1ODk3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIzMjRGRkVBOTFBMDAyRjkxMkE4QzcyOEIyMDJBOTQzQlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MzY5NDU1MDFcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyNTQ3ODQzNTU4OTdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjRDMTI2MzI3RDVFRThERkVDQUI0NkU2NTA5NTYxQzQ0XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTczNjk0NTUwMVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjI1NDc4NDM1NTg5N0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiRTI2QzFFRjNDMzUwRTREN0M2MDIxRDJCMTMwRjMyQTZcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzM2OTQ1NTA1XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjU0Nzg0MzU1ODk3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJCQzcyM0QwNjkxNjNENTI2RDBDNjE2NjdDMERCQ0YzRFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MzY5NDU1MDZcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwid2NMaHh1eS1Tdm1ZNTJzc3gyQ1Y2Z1wiLFxuICBcInBob25lSWRcIjogXCI5MDc5OTI0NS0zMGRlLTQ4YTktYmUwZi1lMjRlYjM2MjkyYTBcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTksXG4gICAgICAyMTQsXG4gICAgICAxOTgsXG4gICAgICAyMixcbiAgICAgIDEyNixcbiAgICAgIDIwMyxcbiAgICAgIDE2MyxcbiAgICAgIDE5LFxuICAgICAgNjcsXG4gICAgICAyNCxcbiAgICAgIDUxLFxuICAgICAgMjA2LFxuICAgICAgMjE2LFxuICAgICAgMzUsXG4gICAgICA1OCxcbiAgICAgIDIzMCxcbiAgICAgIDIwOSxcbiAgICAgIDI1NCxcbiAgICAgIDcwLFxuICAgICAgMTAzXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDczLFxuICAgICAgNTksXG4gICAgICA0OCxcbiAgICAgIDIzMyxcbiAgICAgIDMxLFxuICAgICAgMzcsXG4gICAgICAxMDQsXG4gICAgICAyMTcsXG4gICAgICAxOCxcbiAgICAgIDc0LFxuICAgICAgMCxcbiAgICAgIDEyMCxcbiAgICAgIDksXG4gICAgICA3NCxcbiAgICAgIDk0LFxuICAgICAgMTE1LFxuICAgICAgMTk1LFxuICAgICAgNDQsXG4gICAgICAyMDIsXG4gICAgICA0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIlFLQUJISjNDXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyNTQ3ODQzNTU4OTc6MkBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiNTI4OTc0NTQ3ODA2MDQ6MkBsaWRcIixcbiAgICBcIm5hbWVcIjogXCJTY2hpemFyZDAwXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSnFMek1NRkVOZmVucndHR0FJZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJpc1k2WnNOVnFvQmpEeU9TNEw5U2Nqd1ArRWxaNjdmMWlwZ1lMWkhOd0JRPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcImxaanE4aDBVeDVoaXNtQ3JITWs4Qm9ndXFlZEtNK1hiMEQ3OWNmQ3NDT3cyRTZrVSt1czhQU1k1bkF5a0NmcjhzemcyWHd1bmxNeHF1SVp3S1pOWER3PT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIk9OVVVORjNKRnh2N21xNHM5QXBtSExrN3VMNnJmbEU1Qzh2Y2x0VjVpNHRRQThtSkozYTY3SnM3c2tTVHA1MTE2clVlM0MwMnQremtWcEhHMVNmaEJBPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjI1NDc4NDM1NTg5NzoyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDE5OCxcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMTk1LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICA3MyxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDI0NSxcbiAgICAgICAgICAxMzgsXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDQ1LFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAyMDUsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDIwXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MzY5NDU0OTgsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFPRjJcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU9GMi5qc29uIjogIntcImtleURhdGFcIjpcImtTbEU3Z1RwOHNwWko4UEZiYmFDdVN1Sm4wQURweVhQWG1vV3lqVm10OVk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTQ4MzkzMzA4MixcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzM2OTQyOTE3MTI3XCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "ADAM",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "1",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 5,
  //userImages:process.env.USER_IMAGES|| "https://telegra.ph/file/d0ff3b7eb69827434ce7a.mp4",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "true",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "true", 
  //alwaysonline:process.env.WAPRESENCE|| "available", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "true",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
